#!/bin/bash

WORK_DIR="/global/cfs/projectdirs/atlas/jashley"
cd ${WORK_DIR}
echo "Switched to working directory ${WORK_DIR}"

python mucoll-benchmarks/generation/pgun/pgun_lcio.py -e 1 --pdg 14 --p 100 --theta 10 170 -- output_gen.slcio

ddsim --steeringFile mucoll-benchmarks/simulation/ilcsoft/steer_baseline.py --inputFile output_gen.slcio --outputFile output_sim.slcio

OUTPUT_DIR="/global/cfs/projectdirs/atlas/jashley/mjolnir/data/beta/bg/"
mv output_* ${OUTPUT_DIR}
