#!/bin/bash

WORK_DIR="/global/cfs/projectdirs/atlas/jashley"
cd ${WORK_DIR}
echo "Switched to working directory ${WORK_DIR}"

NUM_EVENTS=$1
STEERING_FILE="mjolnir/code/TrkHitsStudiesWorkspace/configs/digi_steer_MAIAv0.py"
EVENT_FILES="/global/cfs/projectdirs/atlas/arastogi/MuonCollider/data/MAIA/Sim/pt0-5000GeV_n10000_pdg13_MAIA/"
GEOMETRY_FILE="mjolnir/data/geometries/detector-simulation/geometries/MAIA_v0/MAIA_v0.xml"

echo "=== Creating TRAINING files ==="

echo "Feeding ${NUM_EVENTS} event data files into ${STEERING_FILE}"
echo "    Event file source directory: ${EVENT_FILES}"
echo "    Geometry file: ${GEOMETRY_FILE}"

# Pick NUM_EVENTS random files
PICKED_EVENT_FILES=$(ls -1 "${EVENT_FILES}" | shuf | head -n "${NUM_EVENTS}" | sed "s|^|${EVENT_FILES}|")

# Merge selected event files
TRAINING_MERGE_LOG="MAIA-merged-sim-training.log"
date >> ${TRAINING_MERGE_LOG}
echo "${NUM_EVENTS} events:" >> ${TRAINING_MERGE_LOG}
echo ${PICKED_EVENT_FILES} >> ${TRAINING_MERGE_LOG}
SIM_FILE_NAME="MAIA-merged-sim.slcio"
lcio_merge_files ${SIM_FILE_NAME} ${PICKED_EVENT_FILES}

# Run digitization
TRAINING_DIGI_LOG="MAIA-digi.log"
k4run ${STEERING_FILE} --LcioEvent.Files ${SIM_FILE_NAME} --DD4hepXMLFile ${GEOMETRY_FILE} \
	-n ${NUM_EVENTS} | tee ${TRAINING_DIGI_LOG}

# Tidy working directory
OG_DIGI_SLCIO="output_digi_light.slcio"
OG_DIGI_ROOT="output_digi.root"
DIGI_SLCIO="output_digi_light_training.slcio"
DIGI_ROOT="output_digi_training.root"
OUTPUT_DIR="/global/cfs/projectdirs/atlas/jashley/mjolnir/data/beta/MAIA/signal"
mv ${OG_DIGI_SLCIO} "${OUTPUT_DIR}/${DIGI_SLCIO}"
mv ${OG_DIGI_ROOT} "${OUTPUT_DIR}/${DIGI_ROOT}"

echo "=== Creating EVALUATION files ==="

echo "Feeding ${NUM_EVENTS} event data files into ${STEERING_FILE}"
echo "    Event file source directory: ${EVENT_FILES}"
echo "    Geometry file: ${GEOMETRY_FILE}"

# Pick NUM_EVENTS random files
PICKED_EVENT_FILES=$(ls -1 "${EVENT_FILES}" | shuf | head -n "${NUM_EVENTS}" | sed "s|^|${EVENT_FILES}|")

# Merge selected event files
EVAL_MERGE_LOG="MAIA-merged-sim-eval.log"
date >> ${EVAL_MERGE_LOG}
echo "${NUM_EVENTS} events:" >> ${EVAL_MERGE_LOG}
echo ${PICKED_EVENT_FILES} >> ${EVAL_MERGE_LOG}
SIM_FILE_NAME="MAIA-merged-sim.slcio"
lcio_merge_files ${SIM_FILE_NAME} ${PICKED_EVENT_FILES}

# Run digitization
EVAL_DIGI_LOG="MAIA-digi.log"
k4run ${STEERING_FILE} --LcioEvent.Files ${SIM_FILE_NAME} --DD4hepXMLFile ${GEOMETRY_FILE} \
	-n ${NUM_EVENTS} | tee ${EVAL_DIGI_LOG}

# Tidy working directory
OG_DIGI_SLCIO="output_digi_light.slcio"
OG_DIGI_ROOT="output_digi.root"
DIGI_SLCIO="output_digi_light_eval.slcio"
DIGI_ROOT="output_digi_eval.root"
OUTPUT_DIR="/global/cfs/projectdirs/atlas/jashley/mjolnir/data/beta/MAIA/signal"
mv ${OG_DIGI_SLCIO} "${OUTPUT_DIR}/${DIGI_SLCIO}"
mv ${OG_DIGI_ROOT} "${OUTPUT_DIR}/${DIGI_ROOT}"
