#!/bin/bash

WORK_DIR="/global/cfs/projectdirs/atlas/jashley"
cd ${WORK_DIR}
echo "Switched to working directory ${WORK_DIR}"

NUM_EVENTS=$1
GEN_FILE="output_gen_training.slcio"
echo "Generating ${NUM_EVENTS} to ${GEN_FILE}"

python mucoll-benchmarks/generation/pgun/pgun_lcio.py -e ${NUM_EVENTS} --pdg 13 --p 10000 --theta 10 170 -- output_gen_training.slcio

SIM_FILE="output_sim_training.slcio"
SIM_STEER="mucoll-benchmarks/simulation/ilcsoft/steer_baseline.py"
ddsim --steeringFile ${SIM_STEER} --inputFile ${GEN_FILE} --outputFile ${SIM_FILE}

DIGI_STEER="mjolnir/code/TrkHitsStudiesWorkspace/configs/digi_steer_MAIAv0.py"
GEOMETRY_FILE="mjolnir/data/geometries/detector-simulation/geometries/MAIA_v0/MAIA_v0.xml"
k4run ${DIGI_STEER} --LcioEvent.Files ${SIM_FILE} -- DD4hepXMLFile ${GEOMETRY_FILE} -n ${NUM_EVENTS} | tee output_from_term_MAIA_training.txt
